config/routes.rb
Rails.application.routes.draw do

  root 'charts#index'

  resources :charts do 
    resources :artists 
  end

  resources :artists do 
    resources :songs 
  end


end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :chart
  has_many :songs
  validate: :name, uniqueness: true

end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :artists
  validate: :name, uniqueness: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validate: :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_chart
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  
  def index
    @artists = @chart.artists
  end

  def show
  end

  def new
    @artist = @chart.artists.new
  end

  def create
    @artist = @chart.artists.new(artist_params)
    if @artist.save
      redirect_to [@chart, @artist]
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @artist.update(artist_params)
      redirect_to [@chart, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to root_path
  end

  private

  def set_chart
    @chart = Chart.find(params[:chart_id])
  end

  def artist_params
    params.require(:artist).permit(:name, :genre, :group)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

before_action :set_chart, only: [:show, :edit, :update, :destroy]


  def index
    @charts = Chart.all
  end

  def show
  end

  def new
    @chart = Chart.new
  end

  def create
    @chart = Chart.new(chart_params)
    if @chart.save
      redirect_to charts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chart.update(chart_params)
      redirect_to charts_path
    else
      render :edit
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  private

  def chart_params
    params.require(:chart).permit(:name)
  end

  def set_chart
    @chart = Chart.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  
  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @artist = @chart.artists.new
  end

  def create
    @song = @artist.song.new(song_params)
    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to root_path
  end

  private
  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
  def set_song
    @song = Song.find(params[:id])
  end
  def song_params
    params.require(:song).permit(:name, :album, :length)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1> <%= @artist.id ? 'Edit Artist' : 'New Artist' %> </h1>
</br>
<%= form_for [@chart, @artist] do |f| %>


  <%= f.label :chart_id%>
  <%= f.collection_select :chart_id, Chart.order(:name),:id,:name, include_blank: true %>
  <%= f.text_field :chart_id, required: true%>

  <%= f.label :name%>
  <%= f.text_field :name, required: true%>
  

  <%= f.label :genre%>
  <%= f.text_field :genre, required: true%>

  <%= f.label :group%>
  <%= f.check_box :group, required: false%>
  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>All Artists</h1>
<%= link_to 'New Artist', new_chart_artist_path(@chart)%>
<ul>
  <% @artists.each do |artist|%>
    <li>
    <%= link_to artist.name, artist_path(artist) %>
    </li>
  <% end %>

</ul>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1> <%=@artist.name%> </h1>
</br>

<%= link_to 'Edit Artist', edit_artist_path(@artist) %>
</br>

<%= link_to 'Delete Artist', @artist, method: :delete %>
</br>

<%= link_to 'View Songs', artist_songs_path(@artist) %>

app/views/charts/_form.html.erb
<h1> <%= @chart.id ? 'Edit Chart' : 'New Chart' %> </h1>
</br>
<%= form_for @chart do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name, required: true%>
  <%= f.submit %>
<% end %>

app/views/charts/edit.html.erb
<h1>Charts#edit</h1>
<p>Find me in app/views/charts/edit.html.erb</p>

app/views/charts/index.html.erb
<h1>All Charts</h1>
<%= link_to 'New chart', new_chart_path%>
<ul>
  <% @charts.each do |chart|%>
    <li>
    <%= link_to chart.name, chart_path(chart) %>
    </li>
  <% end %>

</ul>

app/views/charts/new.html.erb
<h1>Charts#new</h1>
<p>Find me in app/views/charts/new.html.erb</p>

app/views/charts/show.html.erb
<h1> <%=@chart.name%> </h1>
</br>
<h2> Artists </h2>
<ul>
  <% @chart.artists.each do |artist| %>
    <li>
    <%= link_to artist.name, [@chart, @artist]%>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit Chart', edit_chart_path(@chart) %>
</br>

<%= link_to 'Delete Chart', @chart, method: :delete %>
</br>

<%= link_to 'View Artists', chart_artists_path(@chart) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RapCharts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1> <%=@song.name%> </h1>
<br />

<%= link_to 'Edit Song, edit_song_path(@artist)%>
<br />

<%= link_to 'Delete Artist', @artist, method: :delete %>
<br />

<%= link_to 'Home', root_path